### ISSUE TITLE
TODO: Build Notifications Dropdown

### ISSUE THREAD

**Issue by BanjoFox** [Aardwolf-Social/aardwolf-interface#16]
**Task**
Create an HTML/CSS segment that matches the **notifications dropdown** wireframe.

**Source Image:**
/design_notes/wireframes/notifications_dropdown.png

**File Destination**
/templates/elements/notifications_dropdown.html

**Comment by tomekp97** [comment]
Heya! Mind if I get started on this one?

**Comment by BanjoFox** [comment]
It's all yours! :)
